name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install project dependencies
        run: npm install
        working-directory: ./shiv-react-app

      - name: Run the tests
        run: npm test
        working-directory: ./shiv-react-app


      - name: Build the project
        run: npm run build
        working-directory: ./shiv-react-app

